using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Acme;

/// <summary>
/// Generated by EF Core scaffolding.
/// </summary>
public partial class AcmeDbContext : DbContext
{
	public AcmeDbContext(DbContextOptions<AcmeDbContext> options)
		: base(options)
	{
	}

	public virtual DbSet<Product> Products { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Product>(entity =>
		{
			entity.ToTable("Product");

			entity.HasIndex(e => e.Code, "UQ_ProductCode").IsUnique();

			entity.Property(e => e.Code).HasMaxLength(32);
			entity.Property(e => e.Name).HasMaxLength(100);
		});

		OnModelCreatingPartial(modelBuilder);
	}

	partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}