using System;
using System.Collections.Generic;

namespace Acme;

/// <summary>
/// Generated by EF Core scaffolding.
/// </summary>
public partial class Product
{
    public int Id { get; set; }

    public string Code { get; set; } = null!;

    public string? Name { get; set; }
}
