# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: build-and-publish-package
on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:      
  release:
    types: [created]
   
env:
  BuildConfiguration: "Release"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0   # Fetch all history for all branches and tags, so "git describe" works.

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Get Version from Git Tags (Windows)
      shell: pwsh
      run: |
        git describe --tags --abbrev=0 | Tee-Object -Variable TAG
        $VERSION = $TAG -replace "^v", ""       # We expect the $Tag to look like "v1.2.3", remove the "v".
        echo "VERSION=$VERSION" >> $env:GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore src/DatabaseTestSetManager.sln

    - name: Build
      run: dotnet build src/DatabaseTestSetManager.sln --no-restore --configuration $Env:BuildConfiguration /p:Version=$Env:Version

    - name: Test
      run: dotnet test src/DatabaseTestSetManager.sln --no-build --verbosity normal

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: Binaries
    #     path: src/DatabaseTestSetManager/bin/$BuildConfiguration

    - name: Publish NuGet Package
      # if: github.event_name == 'release'        # Only push when triggered by a release.
      run: dotnet nuget push **\*.nupkg --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate
