# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: build-solution
on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]
env:
  BuildConfiguration: "Release"


jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 20   # Fetch all history for all branches and tags, so "git describe" works.

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Get Version from Git Tags (Windows)
      shell: pwsh
      run: |
        git describe --tags --abbrev=0 | Tee-Object -Variable TAG
        $VERSION = $TAG -replace "^v", ""
        echo "VERSION=$VERSION" >> $env:GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore src/DatabaseTestSetManager.sln

    - name: Build
      run: dotnet build src/DatabaseTestSetManager.sln --configuration $BuildConfiguration /p:Platform="Any CPU" --no-restore

    - name: Test
      run: dotnet test src/DatabaseTestSetManager.sln --no-build --verbosity normal

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Binaries
        path: src/DatabaseTestSetManager/bin/$BuildConfiguration